- name: create a user
  hosts: all
  become: true
  vars_files:
    - secret1.yml
  tasks:
    - name: creating user
      user:
        name: "{{ username }}"
        password: "{{ pwhash | password_hash ('sha512') }}"